# Site settings
title: Laama
subtitle: Lieu d'Accueil pour Animaux Maltraités et Abandonnés
description: >- # this means to ignore newlines until "baseurl:"
  Un refuge pour recueillir les animaux abandonnés, saisis de justice, réhabilités de laboratoire.
  Former les professionnels du milieu animal.
  Sensibiliser le public.

# Contact information
street_address: Aidez nous à trouver une terre d'accueil ! 
city: De préférence à la campagne
state: Rhône Alpes
zip_code: SOS
country: France
phone: (33) 608 286 626
email: info@laama.org

# Social settings
500px_url: https://github.com/apehex
facebook_url: https://github.com/apehex
github_url: https://github.com/apehex
gitlab_url: https://github.com/apehex
googleplus_url: https://github.com/apehex
instagram_url: https://github.com/apehex
linkedin_url: https://github.com/apehex
pinterest_url: https://github.com/apehex
slack_url: https://github.com/apehex
twitter_url: https://github.com/apehex

# Legal Mentions
legal_terms: /legal
privacy_policy: /privacy

# Build settings
theme: jekyll-theme-twenty
markdown: kramdown
sass:
  style: compressed

# Publication settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
author: apehex

# Exclude from processing
