# Site settings
title: Laama
subtitle: Lieu d'Accueil pour Animaux Maltraités et Abandonnés
description: >- # this means to ignore newlines until "baseurl:"
  Un refuge pour recueillir les animaux abandonnés, saisis de justice, réhabilités de laboratoire.
  Former les professionnels du milieu animal.
  Sensibiliser le public.

# Contact information
street_address: 1950 route de Saint Romain
city: Saint Barthélémy le plain
state: Rhône Alpes
zip_code: 07300
country: France
phone: (33) 608 286 626
email: info@laama.org

# Social settings
twitter_url: https://twitter.com/
facebook_url: https://www.facebook.com/LAAMA-392548667977247/
discord_url: https://discord.com/
helloasso_url: https://www.helloasso.com/associations/laama

# Optional elements
logo_url: assets/images/logo.png
legal_terms_url: legal-terms
privacy_policy_url: privacy-policy

# Collections
collections:
  about-us:
    output: true
  help-us:
    output: true
  our-refuge:
    output: true
  the-rescued:
    output: true

# Build settings
theme: jekyll-theme-twenty
markdown: kramdown
sass:
  style: compressed

# Publication settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://apehex.github.io/laama/" # the base hostname & protocol for your site, e.g. http://example.com
permalink: pretty
author: apehex

# Exclude from processing
exlude: [".sass-cache/"]
