# Site settings
title: Laama
subtitle: Lieu d'Accueil pour Animaux Maltraités et Abandonnés
description: >- # this means to ignore newlines until "baseurl:"
  Un refuge pour recueillir les animaux abandonnés, saisis de justice, réhabilités de laboratoire.
  Former les professionnels du milieu animal.
  Sensibiliser le public.

# Contact information
street_address: Aidez nous à trouver une terre d'accueil ! 
city: De préférence à la campagne
state: Rhône Alpes
zip_code: SOS
country: France
phone: (33) 608 286 626
email: info@laama.org

# Social settings
500px_url: https://github.com/moodule
facebook_url: https://github.com/moodule
github_url: https://github.com/moodule
gitlab_url: https://github.com/moodule
googleplus_url: https://github.com/moodule
instagram_url: https://github.com/moodule
linkedin_url: https://github.com/moodule
pinterest_url: https://github.com/moodule
slack_url: https://github.com/moodule
twitter_url: https://github.com/moodule

# Legal Mentions
legal_terms: /legal
privacy_policy: /privacy

# Build settings
theme: jekyll-theme-twenty
markdown: kramdown
sass:
  style: compressed

# Publication settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
author: David Mougeolle

# Exclude from processing
